# Generated by Django 5.0.3 on 2024-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('Image', models.ImageField(default='', upload_to='app/images')),
            ],
        ),
    ]
